mail:
  host: MAIL-HOST
  port: 587
  username: USERNAME
  password: PASSWORD
  from: FROM-ADDRESS
  recipients: [RECIPIENT-ADDRESS#1,RECIPIENT-ADDRESS#2]

slack:
  token: SLACK-TOKEN
  channels: [CHANNEL#1,CHANNEL#2]

telegram:
  token: TELEGRAM-TOKEN
  chatids: [CHATID#1,CHATID#2]

discord:
  webhook_url: DISCORD_WEBHOOK

urlscan:
  token: "APIKEY" # generate from https://urlscan.io/user/profile/
  scanurl: "https://urlscan.io/api/v1/scan/"
  visibility: "private" # public, unlisted, private
  tags: "private.mytag" # comma separated list of tags

global-domain-exclusion:
  exclusion-list: [ebay.com, amazon.com, fust.ch]

queries:
  - query: "ipad"
    expected-domains: [apple.com, amazon.de]

  - query: "as roma"
    expected-domains: []
