mail:
  host: MAILHOST
  port: 587
  username: USERNAME
  password: PASSWORD
  from: FROMADDRESS
  recipients: [RECIPIENTADDRESS#1,RECIPIENTADDRESS#2]

slack:
  token: SLACKTOKEN
  channels: [CHANNEL#1,CHANNEL#2]

telegram:
  token: TELEGRAMTOKEN
  chatids: [CHATID#1,CHATID#2]

urlscan:
  token: "APIKEY" # generate from  https://urlscan.io/user/apikey/
  scanurl: "https://urlscan.io/api/v1/scan/"
  visibility: "private" # public, unlisted, private
  tags: "private.mytag" # comma separated list of tags

queries:
  - query: "ipad"
    expected-domains: [apple.com, amazon.com]

  - query: "as roma"
    expected-domains: []
